### ISSUE TITLE
error installing garfield in ubuntu 16.04 LTS 64 bit

### ISSUE THREAD

**Issue by RamaPrasad999** [brettviren/garfield-build#1] opened 2017-11-27 11:31 UTC
I ran the ./native.sh in my PC for installing garfield. But, I get an error, I have installed the pre-requistic softwares. 
sudo apt-get install cernlib libgsl0-dev nypatchy

The errors are 
rama@ramaPc:~/garfield-build-master$ ./native.sh /home/rama/Gar_build/
Already have patchy_step
Already downloaded garfield-7.cra
Already downloaded garfadd-7.cra
Already downloaded garfield-8.cra
Already downloaded garfadd-8.cra
Already downloaded garfield-9.cra
Already downloaded garfadd-9.cra
Already downloaded garfield-7.car
Already downloaded heed101garf.car
Already downloaded magboltz-2.car
Already downloaded magboltz-3.car
Already downloaded magboltz-7.car
Already downloaded neBEMV1.8.13.tgz
Already downloaded interface.cra
Already downloaded Makefile
Already downloaded garfield.rawhelp
Already downloaded help_input
Already unpacked neBEMV1.8.13.tgz
Patch already applied: neBEMV1.8.13.patch
Already built neBEMV1.8.13
patching file Makefile
Hunk #1 FAILED at 10.
Hunk #2 FAILED at 21.
Hunk #3 FAILED at 36.
Hunk #4 FAILED at 45.
Hunk #5 FAILED at 53.
Hunk #6 FAILED at 67.
Hunk #7 FAILED at 83.
7 out of 7 hunks FAILED -- saving rejects to file Makefile.rej
Error line 60
usage: ./native.sh /path/to/work

The Makefile.rej is attached. 
help me to install.
[Makefile_rej.txt](https://github.com/brettviren/garfield-build/files/1505650/Makefile_rej.txt)

**Comment by brettviren** [comment] 2018-01-09 18:52
It looks like this output is due to re-running `native.sh`.  Although this script tries to be idempotent it's possible a previous run failed in some way that defeats the checks.  I suggest you try removing `Gar_build` or run `native.sh` pointed to an unused location.

I just reran `native.sh` on my Ubuntu 16.04 system and it completed fine.

Also, the `waf` based build works (and is much faster).

I'll close this issue but if the problem isn't the rerunning, feel free to reopen it or make a new one.

**Closed as completed by brettviren** 2018-01-09 18:52 UTC
